// Accelerator Programs Data
// Compiled from official accelerator websites
// Includes city-specific and cause-specific programs

import type { ResourceListing } from "./seed-directory";

export const acceleratorListings: Omit<ResourceListing, "slug">[] = [
  // ============================================
  // NATIONAL / MULTI-CITY ACCELERATORS
  // ============================================
  {
    name: "Y Combinator",
    short_description: "The world's most prestigious startup accelerator, funding early-stage companies.",
    description: "Y Combinator is the world's most successful startup accelerator, having funded companies like Airbnb, Stripe, DoorDash, and Coinbase. YC invests $500,000 in every company for 7% equity and provides intensive 3-month programs with weekly dinners and office hours.",
    category: "accelerator",
    subcategories: ["technology", "seed-stage", "venture-backed"],
    city: "San Francisco",
    state: "CA",
    country: "USA",
    is_remote: true,
    is_nationwide: true,
    website: "https://www.ycombinator.com/",
    details: {
      duration_weeks: 12,
      equity_taken: 7,
      funding_provided: 500000,
      application_url: "https://www.ycombinator.com/apply/",
      deadline: "March and September cohorts",
      type: "venture",
    },
    source: "ycombinator.com",
    source_id: "accelerator-yc",
  },
  {
    name: "Techstars",
    short_description: "Global accelerator network with 13-week programs across multiple cities and industries.",
    description: "Techstars operates accelerator programs in 150+ countries, investing $220,000 in each company for approximately 6% equity. Programs are 13 weeks and include mentorship from industry experts, investor connections, and lifetime membership in the Techstars network.",
    category: "accelerator",
    subcategories: ["technology", "mentorship", "venture-backed"],
    is_remote: true,
    is_nationwide: true,
    website: "https://www.techstars.com/accelerators",
    details: {
      duration_weeks: 13,
      equity_taken: 6,
      funding_provided: 220000,
      application_url: "https://www.techstars.com/accelerators",
      deadline: "Various programs throughout year",
      type: "venture",
    },
    source: "techstars.com",
    source_id: "accelerator-techstars",
  },
  {
    name: "500 Global",
    short_description: "Multi-stage investment firm and accelerator supporting startups worldwide.",
    description: "500 Global (formerly 500 Startups) runs accelerator programs and invests in early-stage startups across all sectors. Programs include seed funding, mentorship, and access to 500 Global's network of founders and investors.",
    category: "accelerator",
    subcategories: ["technology", "seed-stage", "global"],
    city: "San Francisco",
    state: "CA",
    country: "USA",
    is_remote: true,
    is_nationwide: true,
    website: "https://500.co/",
    details: {
      duration_weeks: 16,
      equity_taken: 6,
      funding_provided: 150000,
      application_url: "https://500.co/accelerators",
      deadline: "Rolling applications",
      type: "venture",
    },
    source: "500.co",
    source_id: "accelerator-500-global",
  },
  {
    name: "MassChallenge",
    short_description: "Zero-equity accelerator providing resources and connections to high-impact startups.",
    description: "MassChallenge is a nonprofit accelerator that takes zero equity and provides startups with free resources, mentorship, and access to over $2 million in cash prizes. Programs run in Boston, Israel, Mexico, and Switzerland.",
    category: "accelerator",
    subcategories: ["zero-equity", "nonprofit", "global"],
    city: "Boston",
    state: "MA",
    country: "USA",
    is_remote: false,
    is_nationwide: true,
    website: "https://masschallenge.org/",
    details: {
      duration_weeks: 16,
      equity_taken: 0,
      funding_provided: 0,
      prize_pool: 2000000,
      application_url: "https://masschallenge.org/programs",
      deadline: "Annual cohorts",
      type: "nonprofit",
    },
    source: "masschallenge.org",
    source_id: "accelerator-masschallenge",
  },

  // ============================================
  // AUSTIN, TX ACCELERATORS
  // ============================================
  {
    name: "Capital Factory",
    short_description: "Texas's largest accelerator and coworking space for startups.",
    description: "Capital Factory is the center of gravity for entrepreneurs in Texas. They provide mentorship, coworking space, and connections to investors and corporate partners. Programs include their Accelerator for early-stage companies.",
    category: "accelerator",
    subcategories: ["technology", "coworking", "mentorship"],
    city: "Austin",
    state: "TX",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://www.capitalfactory.com/",
    details: {
      duration_weeks: 12,
      equity_taken: 1,
      application_url: "https://www.capitalfactory.com/accelerator/",
      deadline: "Rolling",
      type: "accelerator",
    },
    source: "capitalfactory.com",
    source_id: "accelerator-capital-factory",
  },
  {
    name: "Techstars Austin",
    short_description: "Techstars accelerator program based in Austin, TX.",
    description: "Techstars Austin brings the global Techstars network to Texas, providing $220,000 investment, 13-week intensive program, and access to mentors and investors focused on the Austin startup ecosystem.",
    category: "accelerator",
    subcategories: ["technology", "venture-backed"],
    city: "Austin",
    state: "TX",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://www.techstars.com/accelerators/austin",
    details: {
      duration_weeks: 13,
      equity_taken: 6,
      funding_provided: 220000,
      application_url: "https://www.techstars.com/accelerators/austin",
      deadline: "Annual cohort",
      type: "venture",
    },
    source: "techstars.com",
    source_id: "accelerator-techstars-austin",
  },
  {
    name: "SKU",
    short_description: "Austin-based accelerator for consumer product companies.",
    description: "SKU is a CPG-focused accelerator based in Austin that helps consumer product companies launch and scale. Program includes mentorship, retail connections, and pitch opportunities.",
    category: "accelerator",
    subcategories: ["consumer-products", "retail", "cpg"],
    city: "Austin",
    state: "TX",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://sku.is/",
    details: {
      duration_weeks: 14,
      equity_taken: 6,
      application_url: "https://sku.is/apply/",
      deadline: "Annual cohort",
      type: "accelerator",
    },
    source: "sku.is",
    source_id: "accelerator-sku",
  },

  // ============================================
  // CHICAGO, IL ACCELERATORS
  // ============================================
  {
    name: "1871",
    short_description: "Chicago's premier technology and entrepreneurship hub.",
    description: "1871 is Chicago's technology and entrepreneurship center, providing programs, workspace, and resources for startups and entrepreneurs. They run accelerator programs, pitch competitions, and education initiatives.",
    category: "accelerator",
    subcategories: ["technology", "coworking", "education"],
    city: "Chicago",
    state: "IL",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://1871.com/",
    details: {
      duration_weeks: 16,
      equity_taken: 0,
      application_url: "https://1871.com/membership/",
      deadline: "Rolling",
      type: "membership",
    },
    source: "1871.com",
    source_id: "accelerator-1871",
  },
  {
    name: "Techstars Chicago",
    short_description: "Techstars accelerator in Chicago for high-growth startups.",
    description: "Techstars Chicago provides $220,000 investment and 13-week intensive program to high-growth startups, connecting them to Chicago's vibrant tech ecosystem and Techstars' global network.",
    category: "accelerator",
    subcategories: ["technology", "venture-backed"],
    city: "Chicago",
    state: "IL",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://www.techstars.com/accelerators/chicago",
    details: {
      duration_weeks: 13,
      equity_taken: 6,
      funding_provided: 220000,
      application_url: "https://www.techstars.com/accelerators/chicago",
      deadline: "Annual cohort",
      type: "venture",
    },
    source: "techstars.com",
    source_id: "accelerator-techstars-chicago",
  },
  {
    name: "MATTER Chicago",
    short_description: "Healthcare technology incubator and innovation hub.",
    description: "MATTER is Chicago's healthcare technology incubator, bringing together startups, hospitals, universities, and industry partners to accelerate innovation in healthcare.",
    category: "accelerator",
    subcategories: ["healthcare", "technology", "innovation"],
    cause_areas: ["health"],
    city: "Chicago",
    state: "IL",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://matter.health/",
    details: {
      equity_taken: 0,
      application_url: "https://matter.health/startups/",
      deadline: "Rolling",
      type: "incubator",
    },
    source: "matter.health",
    source_id: "accelerator-matter-chicago",
  },

  // ============================================
  // ATLANTA, GA ACCELERATORS
  // ============================================
  {
    name: "Atlanta Tech Village",
    short_description: "The South's largest technology hub and startup campus.",
    description: "Atlanta Tech Village is a technology hub and community providing coworking, programming, and resources for startups. They host accelerator programs and connect entrepreneurs with mentors and investors.",
    category: "accelerator",
    subcategories: ["technology", "coworking", "community"],
    city: "Atlanta",
    state: "GA",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://atlantatechvillage.com/",
    details: {
      equity_taken: 0,
      application_url: "https://atlantatechvillage.com/join/",
      deadline: "Rolling",
      type: "incubator",
    },
    source: "atlantatechvillage.com",
    source_id: "accelerator-atlanta-tech-village",
  },
  {
    name: "Startup Runway Foundation",
    short_description: "Accelerator for Black and other underrepresented founders.",
    description: "Startup Runway provides accelerator programs, mentorship, and funding opportunities specifically for Black founders and other underrepresented entrepreneurs in the Southeast.",
    category: "accelerator",
    subcategories: ["diversity", "underrepresented", "mentorship"],
    cause_areas: ["equity"],
    city: "Atlanta",
    state: "GA",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://startuprunway.org/",
    details: {
      duration_weeks: 12,
      equity_taken: 0,
      application_url: "https://startuprunway.org/apply/",
      deadline: "Annual cohorts",
      type: "nonprofit",
    },
    source: "startuprunway.org",
    source_id: "accelerator-startup-runway",
  },
  {
    name: "Techstars Atlanta",
    short_description: "Techstars accelerator program in Atlanta.",
    description: "Techstars Atlanta provides $220,000 investment and 13-week intensive program to startups in Atlanta, with focus on the city's growing tech ecosystem.",
    category: "accelerator",
    subcategories: ["technology", "venture-backed"],
    city: "Atlanta",
    state: "GA",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://www.techstars.com/accelerators/atlanta",
    details: {
      duration_weeks: 13,
      equity_taken: 6,
      funding_provided: 220000,
      application_url: "https://www.techstars.com/accelerators/atlanta",
      deadline: "Annual cohort",
      type: "venture",
    },
    source: "techstars.com",
    source_id: "accelerator-techstars-atlanta",
  },

  // ============================================
  // DENVER / BOULDER, CO ACCELERATORS
  // ============================================
  {
    name: "Techstars Boulder",
    short_description: "The original Techstars accelerator in Boulder, CO.",
    description: "Techstars Boulder was the original Techstars program and remains one of the most competitive accelerators in the world, providing $220,000 investment and access to Boulder's legendary startup community.",
    category: "accelerator",
    subcategories: ["technology", "venture-backed"],
    city: "Boulder",
    state: "CO",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://www.techstars.com/accelerators/boulder",
    details: {
      duration_weeks: 13,
      equity_taken: 6,
      funding_provided: 220000,
      application_url: "https://www.techstars.com/accelerators/boulder",
      deadline: "Annual cohort",
      type: "venture",
    },
    source: "techstars.com",
    source_id: "accelerator-techstars-boulder",
  },
  {
    name: "Boomtown",
    short_description: "Boulder-based accelerator for B2B technology companies.",
    description: "Boomtown is an accelerator focused on B2B technology companies, providing mentorship, investment, and connections to enterprise customers. Programs run in Boulder with a focus on scaling startups.",
    category: "accelerator",
    subcategories: ["b2b", "technology", "enterprise"],
    city: "Boulder",
    state: "CO",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://boomtownaccelerator.com/",
    details: {
      duration_weeks: 12,
      equity_taken: 6,
      funding_provided: 20000,
      application_url: "https://boomtownaccelerator.com/apply/",
      deadline: "Annual cohorts",
      type: "accelerator",
    },
    source: "boomtownaccelerator.com",
    source_id: "accelerator-boomtown",
  },
  {
    name: "Innosphere Ventures",
    short_description: "Colorado's leading technology incubator and accelerator.",
    description: "Innosphere Ventures is Colorado's leading science and technology incubator, providing programs, funding, and mentorship to startups in cleantech, biotech, and software.",
    category: "accelerator",
    subcategories: ["technology", "cleantech", "biotech"],
    cause_areas: ["environment"],
    city: "Fort Collins",
    state: "CO",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://innosphereventures.org/",
    details: {
      duration_weeks: 24,
      equity_taken: 0,
      application_url: "https://innosphereventures.org/companies/apply/",
      deadline: "Rolling",
      type: "incubator",
    },
    source: "innosphereventures.org",
    source_id: "accelerator-innosphere",
  },

  // ============================================
  // MIAMI, FL ACCELERATORS
  // ============================================
  {
    name: "Endeavor Miami",
    short_description: "High-impact entrepreneurship program for scaleups in South Florida.",
    description: "Endeavor Miami selects, mentors, and accelerates high-impact entrepreneurs, providing access to a global network of business leaders, investors, and experts to help companies scale.",
    category: "accelerator",
    subcategories: ["scaleup", "mentorship", "global"],
    city: "Miami",
    state: "FL",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://endeavormiami.org/",
    details: {
      equity_taken: 0,
      application_url: "https://endeavormiami.org/entrepreneurs/",
      deadline: "Rolling",
      type: "nonprofit",
    },
    source: "endeavormiami.org",
    source_id: "accelerator-endeavor-miami",
  },
  {
    name: "500 Miami",
    short_description: "500 Global accelerator program in Miami for LatAm and Florida startups.",
    description: "500 Miami runs accelerator programs connecting Latin American and Florida startups with 500 Global's network of investors, mentors, and resources.",
    category: "accelerator",
    subcategories: ["technology", "latam", "venture-backed"],
    city: "Miami",
    state: "FL",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://500.co/thrive/miami",
    details: {
      duration_weeks: 16,
      equity_taken: 6,
      funding_provided: 150000,
      application_url: "https://500.co/thrive/miami",
      deadline: "Annual cohorts",
      type: "venture",
    },
    source: "500.co",
    source_id: "accelerator-500-miami",
  },
  {
    name: "eMerge Americas",
    short_description: "Miami's tech and innovation hub connecting the Americas.",
    description: "eMerge Americas connects Miami's tech ecosystem with Latin America, hosting accelerator programs, conferences, and investor networking events.",
    category: "accelerator",
    subcategories: ["technology", "latam", "networking"],
    city: "Miami",
    state: "FL",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://emergeamericas.com/",
    details: {
      application_url: "https://emergeamericas.com/",
      deadline: "Annual conference",
      type: "conference",
    },
    source: "emergeamericas.com",
    source_id: "accelerator-emerge-americas",
  },

  // ============================================
  // SEATTLE, WA ACCELERATORS
  // ============================================
  {
    name: "Fledge",
    short_description: "Conscious company accelerator for impact-driven startups.",
    description: "Fledge is a conscious company accelerator supporting entrepreneurs building companies that create positive social and environmental impact. Programs provide mentorship, connections, and small investment.",
    category: "accelerator",
    subcategories: ["social-impact", "sustainability", "conscious-capitalism"],
    cause_areas: ["environment", "equity"],
    city: "Seattle",
    state: "WA",
    country: "USA",
    is_remote: true,
    is_nationwide: true,
    website: "https://fledge.co/",
    details: {
      duration_weeks: 10,
      equity_taken: 5,
      funding_provided: 20000,
      application_url: "https://fledge.co/apply/",
      deadline: "Rolling",
      type: "impact",
    },
    source: "fledge.co",
    source_id: "accelerator-fledge",
  },
  {
    name: "Techstars Seattle",
    short_description: "Techstars accelerator in Seattle, heart of the Pacific Northwest tech scene.",
    description: "Techstars Seattle provides $220,000 investment and 13-week intensive program to startups, leveraging Seattle's strength in cloud, AI, and enterprise technology.",
    category: "accelerator",
    subcategories: ["technology", "venture-backed", "enterprise"],
    city: "Seattle",
    state: "WA",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://www.techstars.com/accelerators/seattle",
    details: {
      duration_weeks: 13,
      equity_taken: 6,
      funding_provided: 220000,
      application_url: "https://www.techstars.com/accelerators/seattle",
      deadline: "Annual cohort",
      type: "venture",
    },
    source: "techstars.com",
    source_id: "accelerator-techstars-seattle",
  },

  // ============================================
  // LOS ANGELES, CA ACCELERATORS
  // ============================================
  {
    name: "Techstars LA",
    short_description: "Techstars accelerator in Los Angeles entertainment and tech hub.",
    description: "Techstars LA provides $220,000 investment and 13-week program to startups, with focus on LA's entertainment, media, and technology ecosystem.",
    category: "accelerator",
    subcategories: ["technology", "entertainment", "venture-backed"],
    city: "Los Angeles",
    state: "CA",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://www.techstars.com/accelerators/los-angeles",
    details: {
      duration_weeks: 13,
      equity_taken: 6,
      funding_provided: 220000,
      application_url: "https://www.techstars.com/accelerators/los-angeles",
      deadline: "Annual cohort",
      type: "venture",
    },
    source: "techstars.com",
    source_id: "accelerator-techstars-la",
  },
  {
    name: "Grid110",
    short_description: "Free accelerator supporting early-stage LA startups.",
    description: "Grid110 is a nonprofit accelerator in Los Angeles providing free programs, mentorship, and resources to early-stage startups, with focus on underrepresented founders.",
    category: "accelerator",
    subcategories: ["early-stage", "nonprofit", "diversity"],
    cause_areas: ["equity"],
    city: "Los Angeles",
    state: "CA",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://grid110.org/",
    details: {
      duration_weeks: 12,
      equity_taken: 0,
      application_url: "https://grid110.org/apply/",
      deadline: "Annual cohorts",
      type: "nonprofit",
    },
    source: "grid110.org",
    source_id: "accelerator-grid110",
  },

  // ============================================
  // WASHINGTON DC ACCELERATORS
  // ============================================
  {
    name: "Halcyon",
    short_description: "DC-based accelerator for social entrepreneurs.",
    description: "Halcyon is a social enterprise accelerator based in Washington DC, providing fellows with 18 months of support, housing, mentorship, and up to $20,000 in no-strings funding.",
    category: "accelerator",
    subcategories: ["social-enterprise", "fellowship", "impact"],
    cause_areas: ["equity", "environment", "education", "health"],
    city: "Washington",
    state: "DC",
    country: "USA",
    is_remote: false,
    is_nationwide: true,
    website: "https://halcyonhouse.org/",
    details: {
      duration_weeks: 78,
      equity_taken: 0,
      funding_provided: 20000,
      application_url: "https://halcyonhouse.org/apply/",
      deadline: "Annual cohorts",
      type: "fellowship",
    },
    source: "halcyonhouse.org",
    source_id: "accelerator-halcyon",
  },
  {
    name: "1776",
    short_description: "Global incubator and accelerator based in DC.",
    description: "1776 is a global incubator and accelerator headquartered in Washington DC, focusing on startups in regulated industries like healthcare, education, energy, and financial services.",
    category: "accelerator",
    subcategories: ["technology", "regulated-industries", "government"],
    city: "Washington",
    state: "DC",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://www.1776.vc/",
    details: {
      equity_taken: 5,
      funding_provided: 100000,
      application_url: "https://www.1776.vc/apply/",
      deadline: "Rolling",
      type: "accelerator",
    },
    source: "1776.vc",
    source_id: "accelerator-1776",
  },

  // ============================================
  // BOSTON, MA ACCELERATORS
  // ============================================
  {
    name: "Techstars Boston",
    short_description: "Techstars accelerator in Boston's innovation hub.",
    description: "Techstars Boston provides $220,000 investment and 13-week intensive program to startups, leveraging Boston's strength in biotech, healthcare, and enterprise technology.",
    category: "accelerator",
    subcategories: ["technology", "venture-backed", "healthcare"],
    city: "Boston",
    state: "MA",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://www.techstars.com/accelerators/boston",
    details: {
      duration_weeks: 13,
      equity_taken: 6,
      funding_provided: 220000,
      application_url: "https://www.techstars.com/accelerators/boston",
      deadline: "Annual cohort",
      type: "venture",
    },
    source: "techstars.com",
    source_id: "accelerator-techstars-boston",
  },
  {
    name: "Harvard Innovation Labs",
    short_description: "Harvard's innovation and entrepreneurship programs.",
    description: "Harvard Innovation Labs provides programs, resources, and community for Harvard students, faculty, and alumni to build ventures and drive innovation.",
    category: "accelerator",
    subcategories: ["education", "university", "innovation"],
    city: "Boston",
    state: "MA",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://innovationlabs.harvard.edu/",
    details: {
      equity_taken: 0,
      application_url: "https://innovationlabs.harvard.edu/",
      deadline: "Academic year programs",
      type: "university",
    },
    source: "harvard.edu",
    source_id: "accelerator-harvard-i-labs",
  },

  // ============================================
  // SAN FRANCISCO / BAY AREA ACCELERATORS
  // ============================================
  {
    name: "StartX",
    short_description: "Stanford-affiliated accelerator for top entrepreneurs.",
    description: "StartX is a nonprofit accelerator affiliated with Stanford University, providing resources, mentorship, and community to Stanford-connected entrepreneurs without taking equity.",
    category: "accelerator",
    subcategories: ["technology", "university", "nonprofit"],
    city: "Palo Alto",
    state: "CA",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://startx.com/",
    details: {
      equity_taken: 0,
      application_url: "https://startx.com/apply/",
      deadline: "Rolling",
      type: "nonprofit",
    },
    source: "startx.com",
    source_id: "accelerator-startx",
  },
  {
    name: "Plug and Play Tech Center",
    short_description: "Silicon Valley accelerator connecting startups with corporations.",
    description: "Plug and Play is a Silicon Valley accelerator and innovation platform connecting startups with over 500 corporate partners across multiple industries.",
    category: "accelerator",
    subcategories: ["technology", "corporate", "venture-backed"],
    city: "Sunnyvale",
    state: "CA",
    country: "USA",
    is_remote: false,
    is_nationwide: true,
    website: "https://www.plugandplaytechcenter.com/",
    details: {
      duration_weeks: 12,
      equity_taken: 0,
      funding_provided: 50000,
      application_url: "https://www.plugandplaytechcenter.com/startups/",
      deadline: "Rolling",
      type: "corporate",
    },
    source: "plugandplaytechcenter.com",
    source_id: "accelerator-plug-and-play",
  },

  // ============================================
  // CLIMATE / CLEAN ENERGY ACCELERATORS
  // ============================================
  {
    name: "Elemental Excelerator",
    short_description: "Climate tech accelerator deploying solutions in Hawaii and beyond.",
    description: "Elemental Excelerator funds, mentors, and deploys climate technology startups, with focus on solutions that can scale in Hawaii and Asia-Pacific markets. Provides up to $1 million in project deployment funding.",
    category: "accelerator",
    subcategories: ["climate", "clean-energy", "deployment"],
    cause_areas: ["environment"],
    city: "Honolulu",
    state: "HI",
    country: "USA",
    is_remote: true,
    is_nationwide: true,
    website: "https://elementalexcelerator.com/",
    details: {
      duration_weeks: 52,
      equity_taken: 0,
      funding_provided: 1000000,
      application_url: "https://elementalexcelerator.com/startups/",
      deadline: "Annual cohorts",
      type: "impact",
    },
    source: "elementalexcelerator.com",
    source_id: "accelerator-elemental",
  },
  {
    name: "Greentown Labs",
    short_description: "Largest climatetech startup incubator in North America.",
    description: "Greentown Labs is the largest climatetech startup incubator in North America, providing lab and prototyping space, community, and resources to help climate entrepreneurs scale.",
    category: "accelerator",
    subcategories: ["climate", "clean-energy", "hardware"],
    cause_areas: ["environment"],
    city: "Somerville",
    state: "MA",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://greentownlabs.com/",
    details: {
      equity_taken: 0,
      application_url: "https://greentownlabs.com/become-a-member/",
      deadline: "Rolling",
      type: "incubator",
    },
    source: "greentownlabs.com",
    source_id: "accelerator-greentown",
  },
  {
    name: "Techstars Sustainability Accelerator",
    short_description: "Techstars program focused on sustainability and climate solutions.",
    description: "Techstars Sustainability accelerators (partnered with various corporations) focus on startups building solutions for climate change, clean energy, and environmental sustainability.",
    category: "accelerator",
    subcategories: ["climate", "sustainability", "venture-backed"],
    cause_areas: ["environment"],
    is_remote: true,
    is_nationwide: true,
    website: "https://www.techstars.com/accelerators",
    details: {
      duration_weeks: 13,
      equity_taken: 6,
      funding_provided: 220000,
      application_url: "https://www.techstars.com/accelerators",
      deadline: "Various programs",
      type: "venture",
    },
    source: "techstars.com",
    source_id: "accelerator-techstars-sustainability",
  },

  // ============================================
  // HEALTH TECH ACCELERATORS
  // ============================================
  {
    name: "Rock Health",
    short_description: "Full-service seed fund for digital health startups.",
    description: "Rock Health is a venture fund and full-service seed fund for digital health startups, providing funding, mentorship, and connections to healthcare industry leaders.",
    category: "accelerator",
    subcategories: ["healthcare", "digital-health", "venture-backed"],
    cause_areas: ["health"],
    city: "San Francisco",
    state: "CA",
    country: "USA",
    is_remote: true,
    is_nationwide: true,
    website: "https://rockhealth.com/",
    details: {
      funding_provided: 250000,
      application_url: "https://rockhealth.com/apply/",
      deadline: "Rolling",
      type: "venture",
    },
    source: "rockhealth.com",
    source_id: "accelerator-rock-health",
  },
  {
    name: "Techstars AI Health Accelerator",
    short_description: "Techstars program focused on AI in healthcare.",
    description: "Techstars AI Health Accelerator, in partnership with health organizations, focuses on startups using artificial intelligence to transform healthcare delivery and outcomes.",
    category: "accelerator",
    subcategories: ["healthcare", "artificial-intelligence", "venture-backed"],
    cause_areas: ["health", "tech-access"],
    city: "Baltimore",
    state: "MD",
    country: "USA",
    is_remote: false,
    is_nationwide: true,
    website: "https://www.techstars.com/accelerators/ai-health",
    details: {
      duration_weeks: 13,
      equity_taken: 6,
      funding_provided: 220000,
      application_url: "https://www.techstars.com/accelerators/ai-health",
      deadline: "Annual cohort",
      type: "venture",
    },
    source: "techstars.com",
    source_id: "accelerator-techstars-ai-health",
  },

  // ============================================
  // FOOD & AGRICULTURE ACCELERATORS
  // ============================================
  {
    name: "Techstars Future of Food",
    short_description: "Accelerator for startups transforming the food system.",
    description: "Techstars Future of Food accelerator, in partnership with Cargill, focuses on startups transforming global food systems through technology, sustainability, and innovation.",
    category: "accelerator",
    subcategories: ["food", "agriculture", "sustainability"],
    cause_areas: ["food-security", "environment"],
    city: "Minneapolis",
    state: "MN",
    country: "USA",
    is_remote: false,
    is_nationwide: true,
    website: "https://www.techstars.com/accelerators/future-of-food",
    details: {
      duration_weeks: 13,
      equity_taken: 6,
      funding_provided: 220000,
      application_url: "https://www.techstars.com/accelerators/future-of-food",
      deadline: "Annual cohort",
      type: "venture",
    },
    source: "techstars.com",
    source_id: "accelerator-techstars-food",
  },
  {
    name: "Food-X",
    short_description: "NYC-based accelerator for food and beverage startups.",
    description: "Food-X is a New York-based accelerator for innovative food and beverage startups, providing investment, mentorship, and connections to retailers and investors.",
    category: "accelerator",
    subcategories: ["food", "consumer-products", "venture-backed"],
    cause_areas: ["food-security"],
    city: "New York",
    state: "NY",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://food-x.com/",
    details: {
      duration_weeks: 16,
      equity_taken: 6,
      funding_provided: 150000,
      application_url: "https://food-x.com/apply/",
      deadline: "Annual cohorts",
      type: "venture",
    },
    source: "food-x.com",
    source_id: "accelerator-food-x",
  },

  // ============================================
  // SOCIAL IMPACT ACCELERATORS
  // ============================================
  {
    name: "Village Capital",
    short_description: "Venture firm investing in entrepreneurs solving global problems.",
    description: "Village Capital is a venture capital firm that invests in entrepreneurs solving real-world problems in agriculture, education, energy, financial services, and health.",
    category: "accelerator",
    subcategories: ["social-impact", "venture-backed", "global"],
    cause_areas: ["education", "health", "food-security", "poverty"],
    is_remote: true,
    is_nationwide: true,
    website: "https://vilcap.com/",
    details: {
      duration_weeks: 12,
      equity_taken: 0,
      funding_provided: 50000,
      application_url: "https://vilcap.com/programs/",
      deadline: "Various programs",
      type: "impact",
    },
    source: "vilcap.com",
    source_id: "accelerator-village-capital",
  },
  {
    name: "Accion Venture Lab",
    short_description: "Venture fund for fintech startups serving underbanked populations.",
    description: "Accion Venture Lab invests in early-stage fintech startups that are expanding financial inclusion for underserved populations around the world.",
    category: "accelerator",
    subcategories: ["fintech", "financial-inclusion", "venture-backed"],
    cause_areas: ["poverty", "equity"],
    is_remote: true,
    is_nationwide: true,
    website: "https://www.accion.org/venture-lab",
    details: {
      funding_provided: 500000,
      application_url: "https://www.accion.org/venture-lab",
      deadline: "Rolling",
      type: "venture",
    },
    source: "accion.org",
    source_id: "accelerator-accion-venture-lab",
  },
  {
    name: "Unreasonable Impact",
    short_description: "Accelerator for growth-stage companies solving global challenges.",
    description: "Unreasonable Impact, in partnership with Barclays, supports growth-stage companies tackling the world's most pressing challenges including climate, employment, and access to resources.",
    category: "accelerator",
    subcategories: ["social-impact", "growth-stage", "global"],
    cause_areas: ["environment", "poverty", "equity"],
    is_remote: true,
    is_nationwide: true,
    website: "https://unreasonablegroup.com/",
    details: {
      equity_taken: 0,
      application_url: "https://unreasonablegroup.com/ventures/",
      deadline: "Annual program",
      type: "impact",
    },
    source: "unreasonablegroup.com",
    source_id: "accelerator-unreasonable",
  },

  // ============================================
  // EDUCATION TECHNOLOGY ACCELERATORS
  // ============================================
  {
    name: "Imagine K12 / Y Combinator EdTech",
    short_description: "Y Combinator's education technology track.",
    description: "Imagine K12 merged with Y Combinator, bringing EdTech focus to YC. Education startups can apply to YC for $500,000 investment and access to the YC network.",
    category: "accelerator",
    subcategories: ["education", "technology", "venture-backed"],
    cause_areas: ["education", "tech-access"],
    city: "San Francisco",
    state: "CA",
    country: "USA",
    is_remote: true,
    is_nationwide: true,
    website: "https://www.ycombinator.com/",
    details: {
      duration_weeks: 12,
      equity_taken: 7,
      funding_provided: 500000,
      application_url: "https://www.ycombinator.com/apply/",
      deadline: "March and September",
      type: "venture",
    },
    source: "ycombinator.com",
    source_id: "accelerator-yc-edtech",
  },
  {
    name: "LearnLaunch",
    short_description: "Boston-based accelerator for education technology startups.",
    description: "LearnLaunch is a Boston-based accelerator focused on education technology, providing programs, workspace, and connections to schools and education organizations.",
    category: "accelerator",
    subcategories: ["education", "technology"],
    cause_areas: ["education"],
    city: "Boston",
    state: "MA",
    country: "USA",
    is_remote: false,
    is_nationwide: false,
    website: "https://learnlaunch.org/",
    details: {
      duration_weeks: 12,
      equity_taken: 0,
      application_url: "https://learnlaunch.org/accelerator/",
      deadline: "Annual cohorts",
      type: "nonprofit",
    },
    source: "learnlaunch.org",
    source_id: "accelerator-learnlaunch",
  },
];

export default acceleratorListings;
