// Grant Programs Data
// Compiled from official sources and grant databases
// Categories: Federal, State, Private Foundation, Corporate

import type { ResourceListing } from "./seed-directory";

export const grantListings: Omit<ResourceListing, "slug">[] = [
  // ============================================
  // FEDERAL GRANTS & PROGRAMS
  // ============================================
  {
    name: "America's Seed Fund (SBIR/STTR)",
    short_description: "Non-dilutive federal funding for small businesses developing innovative technologies.",
    description: "America's Seed Fund powered by the Small Business Administration provides non-dilutive, equity-free funding to small businesses developing cutting-edge technologies. The program is administered through 11 federal agencies including NIH, NSF, DOE, DOD, and NASA. Phase I awards typically range from $50,000-$275,000, and Phase II awards range from $500,000-$1.5M.",
    category: "grant",
    subcategories: ["federal", "technology", "research"],
    cause_areas: ["tech-access"],
    is_remote: true,
    is_nationwide: true,
    website: "https://www.sbir.gov/",
    details: {
      amount_min: 50000,
      amount_max: 1500000,
      eligibility: ["For-profit US business", "Under 500 employees", "51% US-owned"],
      deadline: "Varies by agency",
      type: "federal",
    },
    source: "sbir.gov",
    source_id: "grant-sbir-sttr",
  },
  {
    name: "SBA Community Advantage Loans",
    short_description: "Mission-focused lending for underserved small business communities.",
    description: "SBA Community Advantage loans provide up to $350,000 to small businesses in underserved markets through mission-focused lenders. The program targets businesses in low-to-moderate income areas, veteran-owned, and businesses owned by women and minorities.",
    category: "grant",
    subcategories: ["federal", "lending", "underserved"],
    cause_areas: ["equity"],
    is_remote: true,
    is_nationwide: true,
    website: "https://www.sba.gov/funding-programs/loans/lender-match",
    details: {
      amount_min: 5000,
      amount_max: 350000,
      eligibility: ["Small business in underserved market", "Good credit history"],
      deadline: "Rolling",
      type: "loan",
    },
    source: "sba.gov",
    source_id: "grant-sba-community-advantage",
  },
  {
    name: "USDA Rural Business Development Grants",
    short_description: "Grants to support rural small business development and job creation.",
    description: "USDA Rural Business Development Grants support targeted technical assistance, training, and other activities to benefit small and emerging rural businesses. Grant amounts typically range from $10,000 to $500,000.",
    category: "grant",
    subcategories: ["federal", "rural", "business-development"],
    cause_areas: ["poverty"],
    is_remote: true,
    is_nationwide: true,
    website: "https://www.rd.usda.gov/programs-services/business-programs/rural-business-development-grants",
    details: {
      amount_min: 10000,
      amount_max: 500000,
      eligibility: ["Rural area business", "Town under 50,000 population"],
      deadline: "Varies by state",
      type: "federal",
    },
    source: "usda.gov",
    source_id: "grant-usda-rbdg",
  },
  {
    name: "Economic Development Administration (EDA) Grants",
    short_description: "Federal grants for regional economic development and job creation.",
    description: "EDA provides grants to support economic development, foster job creation, and attract private investment in economically distressed areas. Programs include Public Works, Economic Adjustment Assistance, and Planning grants.",
    category: "grant",
    subcategories: ["federal", "economic-development"],
    cause_areas: ["poverty"],
    is_remote: true,
    is_nationwide: true,
    website: "https://www.eda.gov/funding/programs",
    details: {
      amount_min: 100000,
      amount_max: 3000000,
      eligibility: ["Nonprofits", "Government entities", "Higher education institutions"],
      deadline: "Rolling",
      type: "federal",
    },
    source: "eda.gov",
    source_id: "grant-eda",
  },

  // ============================================
  // WOMEN'S GRANTS
  // ============================================
  {
    name: "Amber Grant for Women",
    short_description: "Monthly $10,000 grants for women-owned businesses.",
    description: "The Amber Grant, offered by WomensNet, awards $10,000 each month to women-owned businesses. At the end of each year, one monthly winner receives an additional $25,000 grand prize. Application fee is $15.",
    category: "grant",
    subcategories: ["women", "small-business"],
    cause_areas: ["equity"],
    is_remote: true,
    is_nationwide: true,
    website: "https://ambergrantsforwomen.com/",
    details: {
      amount_min: 10000,
      amount_max: 25000,
      eligibility: ["Women-owned business", "US-based"],
      deadline: "End of each month",
      type: "private",
      application_fee: 15,
    },
    source: "ambergrantsforwomen.com",
    source_id: "grant-amber",
  },
  {
    name: "Eileen Fisher Women-Owned Business Grant",
    short_description: "Grants for women-owned businesses creating social and environmental change.",
    description: "Eileen Fisher provides grants up to $100,000 to women-owned businesses that are beyond the idea stage and creating positive social and environmental change. Focus areas include sustainability, women's empowerment, and environmental justice.",
    category: "grant",
    subcategories: ["women", "social-impact", "sustainability"],
    cause_areas: ["environment", "equity"],
    is_remote: true,
    is_nationwide: true,
    website: "https://www.eileenfisher.com/grants",
    details: {
      amount_min: 10000,
      amount_max: 100000,
      eligibility: ["Women-owned (51%+)", "In business 3+ years", "Revenue under $1M", "Social/environmental focus"],
      deadline: "Annual, typically February",
      type: "private",
    },
    source: "eileenfisher.com",
    source_id: "grant-eileen-fisher",
  },
  {
    name: "IFundWomen Universal Grant",
    short_description: "Grants and coaching for women entrepreneurs.",
    description: "IFundWomen provides grants, coaching, and access to capital for women entrepreneurs. Grant amounts vary by program, typically ranging from $1,000 to $25,000.",
    category: "grant",
    subcategories: ["women", "coaching", "small-business"],
    cause_areas: ["equity"],
    is_remote: true,
    is_nationwide: true,
    website: "https://ifundwomen.com/grants",
    details: {
      amount_min: 1000,
      amount_max: 25000,
      eligibility: ["Women-owned business", "US-based"],
      deadline: "Various programs throughout year",
      type: "private",
    },
    source: "ifundwomen.com",
    source_id: "grant-ifundwomen",
  },
  {
    name: "Tory Burch Foundation Fellows Program",
    short_description: "Business education and funding for women entrepreneurs.",
    description: "The Tory Burch Foundation Fellows Program provides women entrepreneurs with business education, mentoring, and access to a $100,000 pitch competition. Fellows receive a year of intensive business development support.",
    category: "grant",
    subcategories: ["women", "mentorship", "education"],
    cause_areas: ["equity", "education"],
    is_remote: true,
    is_nationwide: true,
    website: "https://www.toryburchfoundation.org/programs/fellows/",
    details: {
      amount_min: 0,
      amount_max: 100000,
      eligibility: ["Women-owned business", "In business 2+ years", "Revenue $75K-$3M"],
      deadline: "Annual, typically Spring",
      type: "private",
    },
    source: "toryburchfoundation.org",
    source_id: "grant-tory-burch-fellows",
  },
  {
    name: "Women's Business Development Council Launch Pad Grant",
    short_description: "Grants for early-stage women-owned businesses in Connecticut.",
    description: "WBDC Launch Pad provides grants up to $2,500 for women-owned businesses in Connecticut that have been in operation less than two years.",
    category: "grant",
    subcategories: ["women", "early-stage"],
    cause_areas: ["equity"],
    city: "Connecticut",
    state: "CT",
    is_remote: false,
    is_nationwide: false,
    service_areas: ["CT"],
    website: "https://ctwbdc.org/grants/",
    details: {
      amount_min: 500,
      amount_max: 2500,
      eligibility: ["51% women-owned", "CT-headquartered", "In business less than 2 years"],
      deadline: "April 30, 2026",
      type: "state",
    },
    source: "ctwbdc.org",
    source_id: "grant-wbdc-launchpad",
  },

  // ============================================
  // MINORITY & UNDERSERVED GRANTS
  // ============================================
  {
    name: "National Minority Supplier Development Council Business Consortium Fund",
    short_description: "Growth capital for certified minority business enterprises.",
    description: "NMSDC Business Consortium Fund provides growth capital loans from $150,000 to $15 million to certified Minority Business Enterprises (MBEs) seeking to expand their businesses.",
    category: "grant",
    subcategories: ["minority", "growth-capital"],
    cause_areas: ["equity"],
    is_remote: true,
    is_nationwide: true,
    website: "https://nmsdc.org/mbes/business-consortium-fund/",
    details: {
      amount_min: 150000,
      amount_max: 15000000,
      eligibility: ["NMSDC-certified MBE", "3+ years in business", "Revenue $1M+"],
      deadline: "Rolling",
      type: "private",
    },
    source: "nmsdc.org",
    source_id: "grant-nmsdc-bcf",
  },
  {
    name: "Hello Alice Small Business Grants",
    short_description: "Grants for underserved small business owners.",
    description: "Hello Alice partners with major corporations to offer grants ranging from $5,000 to $50,000 to small business owners, with focus on underserved communities including women, minorities, veterans, and LGBTQ+ entrepreneurs.",
    category: "grant",
    subcategories: ["small-business", "underserved"],
    cause_areas: ["equity"],
    is_remote: true,
    is_nationwide: true,
    website: "https://helloalice.com/grants/",
    details: {
      amount_min: 5000,
      amount_max: 50000,
      eligibility: ["Small business owner", "US-based"],
      deadline: "Various programs",
      type: "private",
    },
    source: "helloalice.com",
    source_id: "grant-hello-alice",
  },
  {
    name: "Grants.gov Federal Grants Portal",
    short_description: "Central database for all federal grant opportunities.",
    description: "Grants.gov is the official portal for finding and applying to all federal grants. Small businesses and nonprofits can search thousands of grant opportunities from 26 federal agencies.",
    category: "grant",
    subcategories: ["federal", "database"],
    is_remote: true,
    is_nationwide: true,
    website: "https://www.grants.gov/",
    details: {
      eligibility: ["Varies by grant"],
      deadline: "Various",
      type: "federal-database",
    },
    source: "grants.gov",
    source_id: "grant-grants-gov",
  },

  // ============================================
  // CORPORATE & FOUNDATION GRANTS
  // ============================================
  {
    name: "FedEx Small Business Grant Contest",
    short_description: "Annual grants up to $50,000 for small businesses.",
    description: "FedEx awards over $250,000 in grants annually to small businesses, with the grand prize winner receiving $50,000. Winners are selected through public voting and judge evaluation.",
    category: "grant",
    subcategories: ["corporate", "small-business"],
    is_remote: true,
    is_nationwide: true,
    website: "https://www.fedex.com/en-us/small-business/grant-contest.html",
    details: {
      amount_min: 15000,
      amount_max: 50000,
      eligibility: ["US small business", "For-profit", "6+ months in operation"],
      deadline: "Annual, typically February-March",
      type: "corporate",
    },
    source: "fedex.com",
    source_id: "grant-fedex",
  },
  {
    name: "NASE Growth Grants",
    short_description: "Quarterly grants for NASE members to grow their businesses.",
    description: "The National Association for the Self-Employed provides quarterly Growth Grants up to $4,000 to help members grow their businesses. Grants can be used for marketing, equipment, or expansion.",
    category: "grant",
    subcategories: ["small-business", "growth"],
    is_remote: true,
    is_nationwide: true,
    website: "https://www.nase.org/become-a-member/member-benefits/business-resources/growth-grants",
    details: {
      amount_min: 500,
      amount_max: 4000,
      eligibility: ["NASE member", "Self-employed/micro-business"],
      deadline: "Quarterly",
      type: "membership",
    },
    source: "nase.org",
    source_id: "grant-nase",
  },
  {
    name: "Visa Foundation Grant Program",
    short_description: "Grants supporting financial inclusion and small business growth.",
    description: "Visa Foundation provides grants to organizations working to advance inclusive economies, support small and micro businesses, and promote financial literacy and inclusion worldwide.",
    category: "grant",
    subcategories: ["foundation", "financial-inclusion"],
    cause_areas: ["poverty", "equity"],
    is_remote: true,
    is_nationwide: true,
    website: "https://usa.visa.com/about-visa/visa-foundation.html",
    details: {
      amount_min: 50000,
      amount_max: 500000,
      eligibility: ["501(c)(3) nonprofits", "Focus on financial inclusion"],
      deadline: "By invitation",
      type: "foundation",
    },
    source: "visa.com",
    source_id: "grant-visa-foundation",
  },
  {
    name: "U.S. Chamber of Commerce CO-100 Grant",
    short_description: "Annual $25,000 grand prize for outstanding small businesses.",
    description: "The U.S. Chamber of Commerce CO-100 program recognizes and rewards the top small businesses in America. Grand prize winner receives $25,000, and ten finalists each receive $2,000.",
    category: "grant",
    subcategories: ["small-business", "award"],
    is_remote: true,
    is_nationwide: true,
    website: "https://www.uschamber.com/co/run/business-financing/small-business-grants-and-programs",
    details: {
      amount_min: 2000,
      amount_max: 25000,
      eligibility: ["For-profit", "1+ year in operation", "Under 250 employees", "Revenue under $20M"],
      deadline: "Annual",
      type: "corporate",
    },
    source: "uschamber.com",
    source_id: "grant-uschamber-co100",
  },
  {
    name: "Amex Shop Small Business Grant",
    short_description: "Grants for brick-and-mortar small businesses.",
    description: "American Express Shop Small grants provide $20,000 to small businesses with brick-and-mortar locations. Focus on businesses that have been in operation since at least January 2024 with 20 or fewer employees.",
    category: "grant",
    subcategories: ["small-business", "retail"],
    is_remote: false,
    is_nationwide: true,
    website: "https://www.americanexpress.com/en-us/business/shop-small/",
    details: {
      amount_min: 20000,
      amount_max: 20000,
      eligibility: ["Brick-and-mortar location", "20 or fewer employees", "1+ year in business"],
      deadline: "Annual, typically January",
      type: "corporate",
    },
    source: "americanexpress.com",
    source_id: "grant-amex-shop-small",
  },
  {
    name: "Verizon Small Business Digital Ready Grant",
    short_description: "Grants and digital skills training for small businesses.",
    description: "Verizon Small Business Digital Ready provides $10,000 grants plus free digital skills courses to help small business owners grow their digital presence and capabilities.",
    category: "grant",
    subcategories: ["small-business", "digital", "training"],
    cause_areas: ["tech-access"],
    is_remote: true,
    is_nationwide: true,
    website: "https://www.verizon.com/about/responsibility/digital-inclusion/small-business-digital-ready",
    details: {
      amount_min: 10000,
      amount_max: 10000,
      eligibility: ["Small business owner", "Complete required courses"],
      deadline: "Rolling applications",
      type: "corporate",
    },
    source: "verizon.com",
    source_id: "grant-verizon-digital-ready",
  },
  {
    name: "Start.Pivot.Grow. Micro Grant",
    short_description: "Quarterly $2,500 grants for established small businesses.",
    description: "Start.Pivot.Grow. provides quarterly micro grants of $2,500 to U.S. small businesses that have been in operation for at least two years with $50,000+ annual revenue.",
    category: "grant",
    subcategories: ["small-business", "micro-grant"],
    is_remote: true,
    is_nationwide: true,
    website: "https://startpivotgrow.com/micro-grant",
    details: {
      amount_min: 2500,
      amount_max: 2500,
      eligibility: ["2+ years in business", "$50K+ annual revenue", "US-based"],
      deadline: "Quarterly",
      type: "private",
    },
    source: "startpivotgrow.com",
    source_id: "grant-start-pivot-grow",
  },
  {
    name: "Breva Thrive Grant",
    short_description: "Quarterly $5,000 grants for community-impact businesses.",
    description: "Breva Thrive Grants provide $5,000 quarterly to U.S.-based small businesses generating revenue, with preference for those with community impact.",
    category: "grant",
    subcategories: ["small-business", "community-impact"],
    cause_areas: ["poverty"],
    is_remote: true,
    is_nationwide: true,
    website: "https://breva.io/thrive-grant",
    details: {
      amount_min: 5000,
      amount_max: 5000,
      eligibility: ["Revenue-generating business", "1+ year preferred", "Community impact"],
      deadline: "Quarterly",
      type: "private",
    },
    source: "breva.io",
    source_id: "grant-breva-thrive",
  },

  // ============================================
  // SOCIAL IMPACT & ENVIRONMENTAL GRANTS
  // ============================================
  {
    name: "Patagonia Environmental Grants",
    short_description: "Grants for grassroots environmental activism.",
    description: "Patagonia provides grants to grassroots activist organizations working on environmental causes. Typical grants range from $5,000 to $20,000 for groups with direct-action agendas.",
    category: "grant",
    subcategories: ["environment", "activism", "grassroots"],
    cause_areas: ["environment"],
    is_remote: true,
    is_nationwide: true,
    website: "https://www.patagonia.com/how-we-fund/",
    details: {
      amount_min: 5000,
      amount_max: 20000,
      eligibility: ["Grassroots organization", "Environmental focus", "Direct action agenda"],
      deadline: "April 30 and August 31",
      type: "foundation",
    },
    source: "patagonia.com",
    source_id: "grant-patagonia",
  },
  {
    name: "Ben & Jerry's Foundation Community Action Grants",
    short_description: "Grants for grassroots organizing and community action.",
    description: "Ben & Jerry's Foundation provides grants up to $25,000 to grassroots organizations working on social justice, environmental issues, and community empowerment.",
    category: "grant",
    subcategories: ["social-justice", "community", "grassroots"],
    cause_areas: ["equity", "environment"],
    is_remote: true,
    is_nationwide: true,
    website: "https://benandjerrysfoundation.org/",
    details: {
      amount_min: 1000,
      amount_max: 25000,
      eligibility: ["501(c)(3) nonprofit", "Budget under $500K", "Grassroots organizing"],
      deadline: "Rolling",
      type: "foundation",
    },
    source: "benandjerrysfoundation.org",
    source_id: "grant-ben-jerrys",
  },
  {
    name: "Newman's Own Foundation Grants",
    short_description: "Grants for organizations empowering communities.",
    description: "Newman's Own Foundation donates 100% of profits to charity, providing grants to organizations that empower people and help them take charge of their lives through nutrition, education, and community development.",
    category: "grant",
    subcategories: ["foundation", "community", "nutrition"],
    cause_areas: ["food-security", "education"],
    is_remote: true,
    is_nationwide: true,
    website: "https://newmansownfoundation.org/",
    details: {
      amount_min: 10000,
      amount_max: 250000,
      eligibility: ["501(c)(3) nonprofit", "Focus on nutrition, education, or community empowerment"],
      deadline: "By invitation primarily",
      type: "foundation",
    },
    source: "newmansownfoundation.org",
    source_id: "grant-newmans-own",
  },
  {
    name: "Google.org Impact Challenge",
    short_description: "Major grants for nonprofits using technology for social impact.",
    description: "Google.org Impact Challenge provides grants up to $2 million to nonprofits and social enterprises using technology to address the world's biggest challenges in areas like climate, equity, and economic opportunity.",
    category: "grant",
    subcategories: ["technology", "social-impact", "innovation"],
    cause_areas: ["tech-access", "environment", "equity"],
    is_remote: true,
    is_nationwide: true,
    website: "https://www.google.org/impactchallenge/",
    details: {
      amount_min: 300000,
      amount_max: 2000000,
      eligibility: ["Nonprofit or social enterprise", "Technology-driven solution"],
      deadline: "Varies by challenge",
      type: "corporate",
    },
    source: "google.org",
    source_id: "grant-google-impact-challenge",
  },
  {
    name: "Echoing Green Fellowship",
    short_description: "Seed funding and support for emerging social entrepreneurs.",
    description: "Echoing Green provides $80,000 in seed funding over two years plus leadership development support to emerging social entrepreneurs launching new organizations to drive positive change.",
    category: "grant",
    subcategories: ["social-enterprise", "fellowship", "leadership"],
    cause_areas: ["equity", "environment", "education", "health"],
    is_remote: true,
    is_nationwide: true,
    website: "https://echoinggreen.org/fellowship/",
    details: {
      amount_min: 80000,
      amount_max: 80000,
      eligibility: ["New organization (less than 2 years)", "Full-time commitment", "Social impact focus"],
      deadline: "Annual, typically October",
      type: "fellowship",
    },
    source: "echoinggreen.org",
    source_id: "grant-echoing-green",
  },

  // ============================================
  // MICROLOANS & ALTERNATIVE FUNDING
  // ============================================
  {
    name: "Kiva U.S. Microloans",
    short_description: "0% interest crowdfunded microloans up to $15,000.",
    description: "Kiva provides 0% interest microloans up to $15,000 to small businesses through crowdfunding. Loans are funded by individual lenders worldwide and can be used for inventory, equipment, or working capital.",
    category: "grant",
    subcategories: ["microloan", "crowdfunding"],
    cause_areas: ["poverty", "equity"],
    is_remote: true,
    is_nationwide: true,
    website: "https://www.kiva.org/borrow",
    details: {
      amount_min: 1000,
      amount_max: 15000,
      eligibility: ["US small business", "Social enterprise preferred"],
      deadline: "Rolling",
      type: "microloan",
      interest_rate: "0%",
    },
    source: "kiva.org",
    source_id: "grant-kiva",
  },
  {
    name: "Grameen America Microloans",
    short_description: "Microloans and financial training for women entrepreneurs.",
    description: "Grameen America provides microloans from $500 to $20,000+ along with financial training and savings programs to women entrepreneurs in low-income communities.",
    category: "grant",
    subcategories: ["microloan", "women", "financial-training"],
    cause_areas: ["poverty", "equity"],
    is_remote: false,
    is_nationwide: true,
    website: "https://www.grameenamerica.org/",
    details: {
      amount_min: 500,
      amount_max: 20000,
      eligibility: ["Women entrepreneurs", "Low-income community", "Group lending model"],
      deadline: "Rolling",
      type: "microloan",
    },
    source: "grameenamerica.org",
    source_id: "grant-grameen-america",
  },
  {
    name: "Accion Opportunity Fund Loans",
    short_description: "Affordable small business loans for underserved entrepreneurs.",
    description: "Accion Opportunity Fund provides loans from $5,000 to $250,000 to small business owners who may not qualify for traditional bank loans, with focus on women, minorities, and underserved communities.",
    category: "grant",
    subcategories: ["lending", "underserved"],
    cause_areas: ["poverty", "equity"],
    is_remote: true,
    is_nationwide: true,
    website: "https://www.opportunityfund.org/",
    details: {
      amount_min: 5000,
      amount_max: 250000,
      eligibility: ["Small business owner", "Underserved community focus"],
      deadline: "Rolling",
      type: "lending",
    },
    source: "opportunityfund.org",
    source_id: "grant-accion",
  },
  {
    name: "LiftFund Small Business Loans",
    short_description: "Affordable loans for entrepreneurs who need more than a loan.",
    description: "LiftFund provides loans from $500 to $2 million along with training and mentorship to help small business owners succeed, particularly those underserved by traditional lenders.",
    category: "grant",
    subcategories: ["lending", "mentorship"],
    cause_areas: ["poverty", "equity"],
    is_remote: true,
    is_nationwide: false,
    service_areas: ["TX", "AL", "AR", "FL", "GA", "KY", "LA", "MS", "MO", "NM", "SC", "TN"],
    website: "https://www.liftfund.com/",
    details: {
      amount_min: 500,
      amount_max: 2000000,
      eligibility: ["Small business in service area"],
      deadline: "Rolling",
      type: "lending",
    },
    source: "liftfund.com",
    source_id: "grant-liftfund",
  },

  // ============================================
  // STATE-SPECIFIC GRANTS
  // ============================================
  {
    name: "California Small Business COVID-19 Relief Grant",
    short_description: "Relief grants for California small businesses and nonprofits.",
    description: "California's relief grant program provides grants to small businesses and nonprofits impacted by the pandemic, administered through California's Office of the Small Business Advocate.",
    category: "grant",
    subcategories: ["state", "relief"],
    state: "CA",
    is_remote: false,
    is_nationwide: false,
    service_areas: ["CA"],
    website: "https://calosba.ca.gov/",
    details: {
      amount_min: 5000,
      amount_max: 25000,
      eligibility: ["California business", "Under 50 employees", "Revenue under $5M"],
      deadline: "When funding available",
      type: "state",
    },
    source: "ca.gov",
    source_id: "grant-california-relief",
  },
  {
    name: "Texas Enterprise Fund",
    short_description: "Economic development grants for businesses expanding in Texas.",
    description: "The Texas Enterprise Fund is a cash grant used as a closing tool to attract companies to relocate or expand in Texas, creating new jobs and capital investment.",
    category: "grant",
    subcategories: ["state", "economic-development", "relocation"],
    state: "TX",
    is_remote: false,
    is_nationwide: false,
    service_areas: ["TX"],
    website: "https://gov.texas.gov/business/page/texas-enterprise-fund",
    details: {
      eligibility: ["Business relocating/expanding to Texas", "Job creation commitment"],
      deadline: "Rolling",
      type: "state",
    },
    source: "texas.gov",
    source_id: "grant-texas-enterprise-fund",
  },
  {
    name: "New York State Small Business Seed Funding Grant",
    short_description: "Seed grants for early-stage New York small businesses.",
    description: "Empire State Development provides seed funding grants to help early-stage small businesses in New York access the capital they need to grow.",
    category: "grant",
    subcategories: ["state", "seed-funding"],
    state: "NY",
    is_remote: false,
    is_nationwide: false,
    service_areas: ["NY"],
    website: "https://esd.ny.gov/small-business-programs",
    details: {
      amount_min: 10000,
      amount_max: 100000,
      eligibility: ["New York business", "Early-stage"],
      deadline: "When funding available",
      type: "state",
    },
    source: "ny.gov",
    source_id: "grant-ny-seed",
  },
  {
    name: "Florida Small Business Emergency Bridge Loan",
    short_description: "Emergency bridge loans for Florida small businesses.",
    description: "Florida provides emergency bridge loans to small businesses affected by declared emergencies, helping them maintain operations during recovery.",
    category: "grant",
    subcategories: ["state", "emergency", "bridge-loan"],
    state: "FL",
    is_remote: false,
    is_nationwide: false,
    service_areas: ["FL"],
    website: "https://floridadisaster.org/business/sbelp/",
    details: {
      amount_min: 1000,
      amount_max: 50000,
      eligibility: ["Florida small business", "Impacted by declared emergency"],
      deadline: "During declared emergency",
      type: "state",
    },
    source: "florida.gov",
    source_id: "grant-florida-bridge",
  },
  {
    name: "Illinois Small Business Jobs Creation Tax Credit",
    short_description: "Tax credits for Illinois businesses creating new jobs.",
    description: "Illinois provides tax credits to small businesses that create new full-time jobs in the state, particularly in designated enterprise zones.",
    category: "grant",
    subcategories: ["state", "tax-credit", "job-creation"],
    state: "IL",
    is_remote: false,
    is_nationwide: false,
    service_areas: ["IL"],
    website: "https://www2.illinois.gov/dceo/SmallBizAssistance/Pages/default.aspx",
    details: {
      eligibility: ["Illinois business", "Creating full-time jobs"],
      deadline: "Rolling",
      type: "tax-credit",
    },
    source: "illinois.gov",
    source_id: "grant-illinois-jobs",
  },
  {
    name: "Maryland Small Business Relief Programs",
    short_description: "Various relief and development programs for Maryland small businesses.",
    description: "Maryland provides multiple programs for small businesses including relief grants, development loans, and technical assistance through the Department of Housing and Community Development.",
    category: "grant",
    subcategories: ["state", "relief", "development"],
    state: "MD",
    is_remote: false,
    is_nationwide: false,
    service_areas: ["MD"],
    website: "https://dhcd.maryland.gov/Business/Pages/Small-Business-Grants.aspx",
    details: {
      eligibility: ["Maryland business"],
      deadline: "Various programs",
      type: "state",
    },
    source: "maryland.gov",
    source_id: "grant-maryland-relief",
  },

  // ============================================
  // VETERANS GRANTS
  // ============================================
  {
    name: "StreetShares Foundation Veteran Small Business Award",
    short_description: "Monthly grants for veteran-owned small businesses.",
    description: "StreetShares Foundation provides monthly grants to veteran-owned small businesses, recognizing outstanding veteran entrepreneurs with funding to grow their businesses.",
    category: "grant",
    subcategories: ["veterans", "small-business"],
    cause_areas: ["veterans"],
    is_remote: true,
    is_nationwide: true,
    website: "https://streetsharesfoundation.org/",
    details: {
      amount_min: 1000,
      amount_max: 15000,
      eligibility: ["Veteran-owned business", "US-based"],
      deadline: "Monthly",
      type: "private",
    },
    source: "streetsharesfoundation.org",
    source_id: "grant-streetshares-veteran",
  },
  {
    name: "Warrior Rising Grant",
    short_description: "Grants and mentoring for veteran entrepreneurs.",
    description: "Warrior Rising provides grants, mentorship, and business development resources to veteran entrepreneurs, helping them launch and grow their businesses.",
    category: "grant",
    subcategories: ["veterans", "mentorship"],
    cause_areas: ["veterans"],
    is_remote: true,
    is_nationwide: true,
    website: "https://warriorrising.org/",
    details: {
      amount_min: 2500,
      amount_max: 10000,
      eligibility: ["Veteran-owned business"],
      deadline: "Quarterly",
      type: "private",
    },
    source: "warriorrising.org",
    source_id: "grant-warrior-rising",
  },

  // ============================================
  // INDUSTRY-SPECIFIC GRANTS
  // ============================================
  {
    name: "Walmart Spark Good Local Grants",
    short_description: "Community grants for nonprofits and organizations.",
    description: "Walmart and the Walmart Foundation provide local community grants ranging from $250 to $5,000 to nonprofits, public schools, and government agencies.",
    category: "grant",
    subcategories: ["community", "nonprofit"],
    is_remote: false,
    is_nationwide: true,
    website: "https://walmart.org/how-we-give/local-community-grants",
    details: {
      amount_min: 250,
      amount_max: 5000,
      eligibility: ["501(c)(3)", "Public school or government agency"],
      deadline: "March 15, 2026",
      type: "corporate",
    },
    source: "walmart.org",
    source_id: "grant-walmart-spark-good",
  },
  {
    name: "Faire Small Business Grant",
    short_description: "Grants for independent retailers opening new stores.",
    description: "Faire provides $5,000 grants to independent retail businesses in the US or Canada that opened their first stores in 2024 or plan to open soon.",
    category: "grant",
    subcategories: ["retail", "new-business"],
    is_remote: false,
    is_nationwide: true,
    website: "https://www.faire.com/grants",
    details: {
      amount_min: 5000,
      amount_max: 5000,
      eligibility: ["Independent retailer", "New store in 2024+", "US or Canada"],
      deadline: "March 31",
      type: "corporate",
    },
    source: "faire.com",
    source_id: "grant-faire",
  },
  {
    name: "Wells Fargo Open for Business Fund",
    short_description: "Grants and resources for diverse small businesses.",
    description: "Wells Fargo Open for Business Fund supports diverse small businesses and nonprofits with grants and resources, particularly focusing on minority, women, and veteran-owned businesses.",
    category: "grant",
    subcategories: ["diverse", "small-business"],
    cause_areas: ["equity"],
    is_remote: true,
    is_nationwide: true,
    website: "https://www.wellsfargo.com/about/corporate-responsibility/community-giving/open-for-business-fund/",
    details: {
      amount_min: 5000,
      amount_max: 25000,
      eligibility: ["Diverse small business", "Community development organization"],
      deadline: "Various",
      type: "corporate",
    },
    source: "wellsfargo.com",
    source_id: "grant-wells-fargo-ofb",
  },
];

export default grantListings;
