// SBA Resource Partner Data
// Generated from official SBA.gov and partner websites
// VBOC data: https://www.sba.gov/local-assistance/resource-partners/veterans-business-outreach-centers-vboc
// SCORE data: https://www.score.org/find-a-location

import type { ResourceListing } from "./seed-directory";

// ============================================
// VETERANS BUSINESS OUTREACH CENTERS (VBOCs)
// 31 centers nationwide
// ============================================

export const vbocListings: Omit<ResourceListing, "slug">[] = [
  // New England Region
  {
    name: "Veterans Business Outreach Center of New England",
    short_description: "Free business training and mentoring for veterans, service members, and military spouses in New England.",
    description: "The Veterans Business Outreach Center of New England provides entrepreneurial development services including business training, counseling, and mentorship to veterans, service members, National Guard and Reserve members, and military spouses in Connecticut, Maine, Massachusetts, New Hampshire, Rhode Island, and Vermont.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "69 Milk St. Suite 217",
    city: "Westborough",
    state: "MA",
    zip: "01581",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["CT", "ME", "MA", "NH", "RI", "VT"],
    website: "https://www.vbocnewengland.org/",
    email: "info.vboc@vbocnewengland.org",
    phone: "844-582-2461",
    details: { type: "VBOC", region: "New England" },
    source: "sba.gov",
    source_id: "vboc-new-england",
  },
  // Atlantic Region
  {
    name: "McNulty Veteran Business Center",
    short_description: "Business development services for veterans in New York and New Jersey.",
    description: "The McNulty Veteran Business Center provides entrepreneurial development services to veterans, service members, and military spouses in New Jersey and New York, including business planning, counseling, and access to capital assistance.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "44 Dalliba Ave.",
    city: "Watervliet",
    state: "NY",
    zip: "12189",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["NJ", "NY"],
    website: "https://www.vbocregion2.com/",
    email: "aamoroso@mcnultycenter.org",
    phone: "518-326-6328",
    details: { type: "VBOC", region: "Atlantic" },
    source: "sba.gov",
    source_id: "vboc-mcnulty",
  },
  {
    name: "VBOC for Puerto Rico & U.S. Virgin Islands",
    short_description: "Veteran business services for Puerto Rico and U.S. Virgin Islands.",
    description: "Provides business training, counseling, and resource referrals to veterans, service members, and military spouses in Puerto Rico and the U.S. Virgin Islands.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "171 Carlos Chardon Ave., Suite 407",
    city: "San Juan",
    state: "PR",
    zip: "00918",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["PR", "VI"],
    website: "https://vbocprandusvi.org/",
    email: "rmarin@vbocpr.org",
    phone: "787-705-7963",
    details: { type: "VBOC", region: "Atlantic" },
    source: "sba.gov",
    source_id: "vboc-puerto-rico",
  },
  // Mid-Atlantic Region
  {
    name: "Old Dominion University Veterans Business Outreach Center",
    short_description: "Veteran business support services for Virginia and West Virginia.",
    description: "ODU VBOC provides entrepreneurial development services to veterans, service members, and military spouses in Virginia and West Virginia, including business planning workshops and one-on-one counseling.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "112 Bank St.",
    city: "Norfolk",
    state: "VA",
    zip: "23510",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["VA", "WV"],
    website: "https://www.vbocvirginia.com/",
    email: "vboc@odu.edu",
    phone: "757-683-5505",
    details: { type: "VBOC", region: "Mid-Atlantic" },
    source: "sba.gov",
    source_id: "vboc-odu",
  },
  {
    name: "University of Maryland Veterans Business Outreach Center",
    short_description: "Veteran business support for DC, Maryland, and Delaware.",
    description: "UMD VBOC serves veterans, service members, and military spouses in Washington D.C., Maryland, and Delaware with business counseling, training, and mentorship programs.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "4600 River Rd., Suite 400",
    city: "Riverdale",
    state: "MD",
    zip: "20737",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["DC", "MD", "DE"],
    website: "https://midatlanticvboc.com/",
    email: "veteranbusiness@umd.edu",
    phone: "301-405-6071",
    details: { type: "VBOC", region: "Mid-Atlantic" },
    source: "sba.gov",
    source_id: "vboc-umd",
  },
  {
    name: "VBOC at Pennsylvania State University",
    short_description: "Veteran entrepreneurship support across Pennsylvania.",
    description: "Penn State VBOC provides business development services to veterans, service members, and military spouses throughout Pennsylvania.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "200 Innovation Blvd., Suite 113",
    city: "University Park",
    state: "PA",
    zip: "16802",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["PA"],
    website: "https://vboc.psu.edu/",
    phone: "814-863-9120",
    details: { type: "VBOC", region: "Mid-Atlantic" },
    source: "sba.gov",
    source_id: "vboc-psu",
  },
  // Southeast Region
  {
    name: "Veterans Business Outreach Center at Gulf Coast State College",
    short_description: "Veteran business services throughout Florida.",
    description: "Gulf Coast VBOC provides workshops, training, counseling, and mentorship to veterans, service members, and military spouses across Florida.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "5230 US Hwy. 98, Student Union West, Rooms 326-330",
    city: "Panama City",
    state: "FL",
    zip: "32401",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["FL"],
    website: "https://vboc.org/",
    email: "bpeacock@gulfcoast.edu",
    phone: "800-542-7232",
    details: { type: "VBOC", region: "Southeast" },
    source: "sba.gov",
    source_id: "vboc-gulf-coast",
  },
  {
    name: "Veterans Business Outreach Center at Fayetteville State University",
    short_description: "Veteran business development services for North Carolina.",
    description: "FSU VBOC provides entrepreneurial development services to veterans, service members, and military spouses in North Carolina.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "1073 Murchison Rd.",
    city: "Fayetteville",
    state: "NC",
    zip: "28301",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["NC"],
    website: "http://www.fsuvboc.com/",
    email: "rlivings@uncfsu.edu",
    phone: "910-672-2683",
    details: { type: "VBOC", region: "Southeast" },
    source: "sba.gov",
    source_id: "vboc-fsu",
  },
  {
    name: "Veterans Business Outreach Center at Pathway Lending",
    short_description: "Veteran business support for Tennessee and Kentucky.",
    description: "Pathway Lending VBOC serves veterans, service members, and military spouses in Tennessee and Kentucky with business training, counseling, and access to capital.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training", "lending"],
    cause_areas: ["veterans"],
    address: "201 Venture Cir.",
    city: "Nashville",
    state: "TN",
    zip: "37228",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["TN", "KY"],
    website: "http://www.pathwaylending.org/vboc",
    email: "vboc@pathwaylending.org",
    phone: "615-916-4809",
    details: { type: "VBOC", region: "Southeast" },
    source: "sba.gov",
    source_id: "vboc-pathway",
  },
  {
    name: "Veterans Business Outreach Center at Mississippi State University",
    short_description: "Veteran business services for Alabama, Louisiana, and Mississippi.",
    description: "MSU VBOC provides entrepreneurial development services to veterans, service members, and military spouses in Alabama, Louisiana, and Mississippi.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "60 Technology Blvd., Suite 105C",
    city: "Starkville",
    state: "MS",
    zip: "39759",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["AL", "LA", "MS"],
    website: "http://www.vboc.msstate.edu/",
    email: "vboc@business.msstate.edu",
    phone: "662-325-4990",
    details: { type: "VBOC", region: "Southeast" },
    source: "sba.gov",
    source_id: "vboc-msu",
  },
  {
    name: "VECTR Center - Veterans Education Career Transition Resource Center",
    short_description: "Veteran business and career transition services for Georgia.",
    description: "VECTR Center provides business development and career transition services to veterans, service members, and military spouses in Georgia.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training", "career"],
    cause_areas: ["veterans"],
    address: "1001 S. Armed Forces Blvd.",
    city: "Warner Robins",
    state: "GA",
    zip: "31088",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["GA"],
    website: "https://www.gavectr.org/vboc",
    email: "reginald.thompson@gavectr.org",
    phone: "833-448-3287",
    details: { type: "VBOC", region: "Southeast" },
    source: "sba.gov",
    source_id: "vboc-vectr",
  },
  {
    name: "South Carolina Veterans Business Outreach Center",
    short_description: "Veteran business development services for South Carolina.",
    description: "The Citadel's VBOC provides entrepreneurial support to veterans, service members, and military spouses throughout South Carolina.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "89 Hagood Ave.",
    city: "Charleston",
    state: "SC",
    zip: "29409",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["SC"],
    website: "https://vboc.citadel.edu/",
    email: "scvboc@citadel.edu",
    phone: "843-953-5867",
    details: { type: "VBOC", region: "Southeast" },
    source: "sba.gov",
    source_id: "vboc-citadel",
  },
  // Great Lakes Region
  {
    name: "ECDI's Veterans Business Outreach Center of Ohio",
    short_description: "Veteran business support services throughout Ohio.",
    description: "ECDI VBOC provides business counseling, training, and mentorship to veterans, service members, and military spouses in Ohio.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "Allyn Hall 131, 3640 Colonel Glenn Hwy.",
    city: "Dayton",
    state: "OH",
    zip: "45435",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["OH"],
    website: "http://ecdi.org/vboc",
    email: "vboc@ecdi.org",
    phone: "888-210-3039",
    details: { type: "VBOC", region: "Great Lakes" },
    source: "sba.gov",
    source_id: "vboc-ecdi",
  },
  {
    name: "VetBiz Central",
    short_description: "Veteran business services for Indiana and Michigan.",
    description: "VetBiz Central provides entrepreneurial development services to veterans, service members, and military spouses in Indiana and Michigan.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "1401 East Court St.",
    city: "Flint",
    state: "MI",
    zip: "48503",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["IN", "MI"],
    website: "http://www.vetbizcentral.org/",
    email: "info@vetbizcentral.org",
    phone: "810-767-8387",
    details: { type: "VBOC", region: "Great Lakes" },
    source: "sba.gov",
    source_id: "vboc-vetbiz-central",
  },
  {
    name: "Wisconsin Women's Business Initiative Corporation VBOC",
    short_description: "Veteran business support for Illinois, Minnesota, and Wisconsin.",
    description: "WWBIC VBOC provides business training, counseling, and access to capital for veterans, service members, and military spouses in Illinois, Minnesota, and Wisconsin.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training", "lending"],
    cause_areas: ["veterans"],
    address: "1533 N Rivercenter Dr.",
    city: "Milwaukee",
    state: "WI",
    zip: "53212",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["IL", "MN", "WI"],
    website: "http://www.wwbic.com/veterans",
    email: "vboc@wwbic.com",
    phone: "414-395-4556",
    details: { type: "VBOC", region: "Great Lakes" },
    source: "sba.gov",
    source_id: "vboc-wwbic",
  },
  // South Central Region
  {
    name: "Veterans Business Outreach Center at UT Rio Grande Valley",
    short_description: "Veteran business services for Central, West, and Southern Texas.",
    description: "UTRGV VBOC provides entrepreneurial development services to veterans, service members, and military spouses in Central, West, and Southern Texas.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "1407 E Freddy Gonzalez Dr., Ste 1200",
    city: "Edinburg",
    state: "TX",
    zip: "78539",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["TX"],
    website: "http://www.utrgv.edu/vboc",
    email: "vboc@utrgv.edu",
    phone: "956-665-8931",
    details: { type: "VBOC", region: "South Central", coverage: "Central, West & Southern Texas" },
    source: "sba.gov",
    source_id: "vboc-utrgv",
  },
  {
    name: "Veterans Business Outreach Center at UT Arlington",
    short_description: "Veteran business support for Arkansas, Northern Texas, and Oklahoma.",
    description: "UTA VBOC provides entrepreneurial development services to veterans, service members, and military spouses in Arkansas, Northern Texas, and Oklahoma.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "701 S West St., Ste 635",
    city: "Arlington",
    state: "TX",
    zip: "76019",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["AR", "TX", "OK"],
    website: "https://vboc.uta.edu/",
    email: "utavboc@uta.edu",
    phone: "817-272-6789",
    details: { type: "VBOC", region: "South Central", coverage: "Arkansas, Northern Texas, Oklahoma" },
    source: "sba.gov",
    source_id: "vboc-uta",
  },
  {
    name: "New Mexico Veterans Business Outreach Center",
    short_description: "Veteran business development services for New Mexico.",
    description: "NM VBOC provides entrepreneurial support to veterans, service members, and military spouses throughout New Mexico.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "4801 Indian School Rd. NE, Building 2, Second Floor",
    city: "Albuquerque",
    state: "NM",
    zip: "87110",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["NM"],
    website: "http://www.nmvboc.org/",
    email: "johnny.martinez@dvs.nm.gov",
    phone: "505-469-8501",
    details: { type: "VBOC", region: "South Central" },
    source: "sba.gov",
    source_id: "vboc-nm",
  },
  // Great Plains Region
  {
    name: "VetBiz",
    short_description: "Veteran business services for Kansas and Missouri.",
    description: "VetBiz provides entrepreneurial development services to veterans, service members, and military spouses in Kansas and Missouri.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "4220 Duncan Ave., Suite 201",
    city: "St. Louis",
    state: "MO",
    zip: "63110",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["KS", "MO"],
    website: "https://vetbiz.com/",
    email: "Info@vetbiz.com",
    phone: "314-531-8387",
    details: { type: "VBOC", region: "Great Plains" },
    source: "sba.gov",
    source_id: "vboc-vetbiz",
  },
  {
    name: "Nebraska Veterans Business Outreach Center",
    short_description: "Veteran business support for Nebraska and Iowa.",
    description: "Nebraska VBOC provides business counseling, training, and mentorship to veterans, service members, and military spouses in Nebraska and Iowa.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "2112 N. 30th St., Suite 103",
    city: "Omaha",
    state: "NE",
    zip: "68111",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["NE", "IA"],
    website: "https://nebbiz.org/vboc",
    email: "nef@nebbiz.org",
    phone: "402-685-5500",
    details: { type: "VBOC", region: "Great Plains" },
    source: "sba.gov",
    source_id: "vboc-nebraska",
  },
  // Rocky Mountain Region
  {
    name: "Big Sky Economic Development Authority VBOC",
    short_description: "Veteran business services for Montana, Utah, and Wyoming.",
    description: "Big Sky VBOC provides entrepreneurial development services to veterans, service members, and military spouses in Montana, Utah, and Wyoming.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "201 N. Broadway",
    city: "Billings",
    state: "MT",
    zip: "59101",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["MT", "UT", "WY"],
    website: "https://bigskyvboc.org/",
    email: "info@vbocregion8.com",
    phone: "406-869-8411",
    details: { type: "VBOC", region: "Rocky Mountain" },
    source: "sba.gov",
    source_id: "vboc-bigsky",
  },
  {
    name: "VBOC of the Dakotas",
    short_description: "Veteran business support for North Dakota and South Dakota.",
    description: "Dakotas VBOC provides business development services to veterans, service members, and military spouses in North Dakota and South Dakota.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "4200 James Ray Dr.",
    city: "Grand Forks",
    state: "ND",
    zip: "58202",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["ND", "SD"],
    website: "https://www.und.edu/dakotasvboc",
    email: "dakotas.vboc@und.edu",
    phone: "701-738-4850",
    details: { type: "VBOC", region: "Rocky Mountain" },
    source: "sba.gov",
    source_id: "vboc-dakotas",
  },
  {
    name: "Colorado Veterans Business Outreach Center",
    short_description: "Veteran business development services for Colorado.",
    description: "Colorado VBOC provides entrepreneurial support to veterans, service members, and military spouses throughout Colorado.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "530 Communication Cir.",
    city: "Colorado Springs",
    state: "CO",
    zip: "80905",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["CO"],
    website: "https://www.veteranscenter.org/vboc/",
    email: "vboc@mtcarmelcenter.org",
    phone: "719-772-7000",
    details: { type: "VBOC", region: "Rocky Mountain" },
    source: "sba.gov",
    source_id: "vboc-colorado",
  },
  // Pacific Region
  {
    name: "NorCal Veterans Business Outreach Center",
    short_description: "Veteran business services for Northern California.",
    description: "NorCal VBOC provides entrepreneurial development services to veterans, service members, and military spouses in Northern California (all counties north of Santa Barbara, Ventura, Los Angeles, and San Bernardino).",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "1792 Tribute Rd., Suite 400",
    city: "Sacramento",
    state: "CA",
    zip: "95815",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["CA"],
    website: "https://norcalvboc.org/",
    email: "info@norcalvboc.org",
    phone: "916-527-8400",
    details: { type: "VBOC", region: "Pacific", coverage: "Northern California" },
    source: "sba.gov",
    source_id: "vboc-norcal",
  },
  {
    name: "SoCal Veterans Business Outreach Center",
    short_description: "Veteran business services for Southern California.",
    description: "SoCal VBOC provides entrepreneurial development services to veterans, service members, and military spouses in Southern California.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "3333 Manchester Ave., Suite 800",
    city: "Cardiff",
    state: "CA",
    zip: "92007",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["CA"],
    website: "https://socalvboc.org/",
    email: "socalvboc@miracosta.edu",
    phone: "760-795-8739",
    details: { type: "VBOC", region: "Pacific", coverage: "Southern California" },
    source: "sba.gov",
    source_id: "vboc-socal",
  },
  {
    name: "Arizona Veterans Business Outreach Center",
    short_description: "Veteran business development services for Arizona.",
    description: "Arizona VBOC provides entrepreneurial support to veterans, service members, and military spouses throughout Arizona.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "635 East Broadway Rd.",
    city: "Mesa",
    state: "AZ",
    zip: "85204",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["AZ"],
    website: "http://www.arizonavboc.org/",
    email: "admin@arizonavboc.org",
    phone: "480-322-4634",
    details: { type: "VBOC", region: "Pacific" },
    source: "sba.gov",
    source_id: "vboc-arizona",
  },
  {
    name: "Veterans Business Outreach Center of the Pacific",
    short_description: "Veteran business services for Hawaii, Guam, and American Samoa.",
    description: "Pacific VBOC provides entrepreneurial development services to veterans, service members, and military spouses in Hawaii, Guam, and American Samoa.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "2800 Woodlawn Dr., Suite 165",
    city: "Honolulu",
    state: "HI",
    zip: "96822",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["HI", "GU", "AS"],
    website: "https://hilo.hawaii.edu/vboc",
    email: "vboc@hawaii.edu",
    phone: "808-988-1236",
    details: { type: "VBOC", region: "Pacific" },
    source: "sba.gov",
    source_id: "vboc-pacific",
  },
  {
    name: "Los Angeles Regional Veterans Business Outreach Center",
    short_description: "Veteran business services for LA and surrounding counties.",
    description: "LA VBOC provides entrepreneurial development services to veterans, service members, and military spouses in Los Angeles, Orange, Riverside, San Bernardino, Santa Barbara, and Ventura Counties.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "4900 E. Conant St., Bldg. O2",
    city: "Long Beach",
    state: "CA",
    zip: "90808",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["CA"],
    website: "https://lavboc.org/",
    email: "info@lavboc.org",
    phone: "844-595-8262",
    details: { type: "VBOC", region: "Pacific", coverage: "LA, Orange, Riverside, San Bernardino, Santa Barbara, Ventura Counties" },
    source: "sba.gov",
    source_id: "vboc-la",
  },
  {
    name: "Nevada Veterans Business Outreach Center",
    short_description: "Veteran business development services for Nevada.",
    description: "Nevada VBOC provides entrepreneurial support to veterans, service members, and military spouses throughout Nevada.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "1664 N. Virginia St.",
    city: "Reno",
    state: "NV",
    zip: "89557",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["NV"],
    website: "https://www.nvvboc.org/",
    email: "lurdes.madrigal@nvvboc.org",
    phone: "833-880-7800",
    details: { type: "VBOC", region: "Pacific" },
    source: "sba.gov",
    source_id: "vboc-nevada",
  },
  // Pacific Northwest Region
  {
    name: "Business Impact NW VBOC",
    short_description: "Veteran business services for Washington, Oregon, and Idaho.",
    description: "Business Impact NW VBOC provides coaching, classes, and capital assistance to veteran small business owners in Washington, Oregon, and Idaho.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training", "lending"],
    cause_areas: ["veterans"],
    address: "12720 Gateway Dr. A, Suite 207",
    city: "Tukwila",
    state: "WA",
    zip: "98168",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["WA", "OR", "ID"],
    website: "https://businessimpactnw.org/vboc/",
    email: "vboc@businessimpactnw.org",
    phone: "206-324-4330",
    details: { type: "VBOC", region: "Pacific Northwest" },
    source: "sba.gov",
    source_id: "vboc-binw",
  },
  {
    name: "Alaska Veterans Business Outreach Center",
    short_description: "Veteran business development services for Alaska.",
    description: "Alaska VBOC provides entrepreneurial support to veterans, service members, and military spouses throughout Alaska.",
    category: "sba",
    subcategories: ["veterans", "mentorship", "training"],
    cause_areas: ["veterans"],
    address: "911 W 8th Ave.",
    city: "Anchorage",
    state: "AK",
    zip: "99501",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    service_areas: ["AK"],
    website: "https://businessimpactnw.org/vboc/",
    email: "vboc@businessimpactnw.org",
    phone: "907-891-7466",
    details: { type: "VBOC", region: "Pacific Northwest" },
    source: "sba.gov",
    source_id: "vboc-alaska",
  },
];

// ============================================
// SCORE CHAPTERS
// 164 chapters nationwide
// ============================================

export const scoreListings: Omit<ResourceListing, "slug">[] = [
  {
    name: "SCORE Akron & Canton",
    short_description: "Free business mentoring and workshops for entrepreneurs in Northeast Ohio.",
    description: "SCORE Akron & Canton provides free, confidential business mentoring and low-cost workshops to help small businesses start and grow in Summit, Stark, Mahoning, Medina, Portage, Wayne, Columbiana, Tuscarawas, Holmes, Carroll, and Harrison counties.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    address: "6200 Frank Ave NW, Suite M331",
    city: "North Canton",
    state: "OH",
    zip: "44720",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/akroncanton",
    phone: "(330) 379-3163",
    details: { type: "SCORE" },
    source: "score.org",
    source_id: "score-akroncanton",
  },
  {
    name: "SCORE Alabama",
    short_description: "Statewide free business mentoring for Alabama entrepreneurs.",
    description: "SCORE Alabama provides virtual business mentoring and workshops to entrepreneurs across the state of Alabama. 2024 Chapter of the Year.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    city: "Birmingham",
    state: "AL",
    zip: "35203",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/alabama",
    phone: "251-385-6667",
    details: { type: "SCORE", virtual_only: true },
    source: "score.org",
    source_id: "score-alabama",
  },
  {
    name: "SCORE Albuquerque",
    short_description: "Free business mentoring for entrepreneurs in Central New Mexico.",
    description: "SCORE Albuquerque provides free business counseling and workshops to entrepreneurs in Bernalillo, Sandoval, Torrance, and Valencia counties.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    address: "3705 Ellison Drive NW, Suite B-1, #188",
    city: "Albuquerque",
    state: "NM",
    zip: "87114",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/albuquerque",
    phone: "505-510-5559",
    details: { type: "SCORE" },
    source: "score.org",
    source_id: "score-albuquerque",
  },
  {
    name: "SCORE Ann Arbor Area",
    short_description: "Free business mentoring for Southeast Michigan entrepreneurs.",
    description: "SCORE Ann Arbor Area provides free, confidential business mentoring to entrepreneurs in Washtenaw, Lenawee, Livingston, Jackson, and Ingham county areas.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    address: "1100 North Main St, Suite 109",
    city: "Ann Arbor",
    state: "MI",
    zip: "48104",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/annarborarea",
    phone: "(734) 929-1121",
    details: { type: "SCORE" },
    source: "score.org",
    source_id: "score-annarborarea",
  },
  {
    name: "SCORE Arkansas",
    short_description: "Statewide free business mentoring for Arkansas entrepreneurs.",
    description: "SCORE Arkansas provides free business counseling and workshops to entrepreneurs across the state of Arkansas.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    address: "2120 Riverfront Drive",
    city: "Little Rock",
    state: "AR",
    zip: "72202",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/arkansas",
    phone: "(501) 209-7870",
    details: { type: "SCORE" },
    source: "score.org",
    source_id: "score-arkansas",
  },
  {
    name: "SCORE Asheville",
    short_description: "Free business mentoring for Western North Carolina entrepreneurs.",
    description: "SCORE Asheville provides free business counseling and workshops to entrepreneurs in the Asheville area and High Country of North Carolina.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    address: "1465 Sand Hill Rd., Suite 2040",
    city: "Candler",
    state: "NC",
    zip: "28715",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/asheville",
    phone: "(828) 417-0555",
    details: { type: "SCORE" },
    source: "score.org",
    source_id: "score-asheville",
  },
  {
    name: "SCORE Atlanta",
    short_description: "Free business mentoring for Metro Atlanta entrepreneurs.",
    description: "SCORE Atlanta provides free, confidential business mentoring to entrepreneurs in Fulton, DeKalb, Clayton, Henry, Fayette counties and the City of Atlanta.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    city: "Atlanta",
    state: "GA",
    zip: "30303",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/atlanta",
    phone: "1-800-634-0245",
    details: { type: "SCORE", virtual_only: true },
    source: "score.org",
    source_id: "score-atlanta",
  },
  {
    name: "SCORE Austin",
    short_description: "Free business mentoring for Central Texas entrepreneurs.",
    description: "SCORE Austin provides free business counseling and workshops to small businesses from Waco to San Marcos in Central Texas.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    address: "PO Box 2322",
    city: "Georgetown",
    state: "TX",
    zip: "78627",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/austin",
    phone: "(512) 928-2425",
    details: { type: "SCORE" },
    source: "score.org",
    source_id: "score-austin",
  },
  {
    name: "SCORE Boston",
    short_description: "Free business mentoring for Greater Boston entrepreneurs.",
    description: "SCORE Boston helps businesses start, grow, and thrive with free, confidential business mentoring and workshops in the Greater Boston area.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    address: "10 Causeway Street",
    city: "Boston",
    state: "MA",
    zip: "02222",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/boston",
    phone: "(617) 565-5591",
    details: { type: "SCORE" },
    source: "score.org",
    source_id: "score-boston",
  },
  {
    name: "SCORE Broward",
    short_description: "Free business mentoring for Broward County entrepreneurs.",
    description: "SCORE Broward helps businesses start, grow, and thrive with free, confidential business mentoring and workshops in Broward County, Florida.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    address: "6565 Taft St, Suite 403",
    city: "Hollywood",
    state: "FL",
    zip: "33024",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/broward",
    phone: "(954) 589-5293",
    details: { type: "SCORE" },
    source: "score.org",
    source_id: "score-broward",
  },
  {
    name: "SCORE Cape Cod & the Islands",
    short_description: "Free business mentoring for Cape Cod, Martha's Vineyard, and Nantucket.",
    description: "SCORE Cape Cod provides free business counseling to entrepreneurs in all towns in Barnstable County, Martha's Vineyard, and Nantucket.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    address: "PO BOX 627",
    city: "West Falmouth",
    state: "MA",
    zip: "02574",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/capecod",
    phone: "508-775-4884",
    details: { type: "SCORE" },
    source: "score.org",
    source_id: "score-capecod",
  },
  // Major city chapters
  {
    name: "SCORE Chicago",
    short_description: "Free business mentoring for Chicago area entrepreneurs.",
    description: "SCORE Chicago provides free, confidential business mentoring and workshops to help small businesses start and grow in the Chicago metropolitan area.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    city: "Chicago",
    state: "IL",
    zip: "60601",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/chicago",
    phone: "1-800-634-0245",
    details: { type: "SCORE" },
    source: "score.org",
    source_id: "score-chicago",
  },
  {
    name: "SCORE Dallas",
    short_description: "Free business mentoring for Dallas/Fort Worth entrepreneurs.",
    description: "SCORE Dallas provides free business counseling and workshops to entrepreneurs in the Dallas/Fort Worth metropolitan area.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    city: "Dallas",
    state: "TX",
    zip: "75201",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/dallas",
    phone: "1-800-634-0245",
    details: { type: "SCORE" },
    source: "score.org",
    source_id: "score-dallas",
  },
  {
    name: "SCORE Denver",
    short_description: "Free business mentoring for Denver area entrepreneurs.",
    description: "SCORE Denver provides free, confidential business mentoring and workshops to help small businesses start and grow in the Denver metropolitan area.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    city: "Denver",
    state: "CO",
    zip: "80202",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/denver",
    phone: "1-800-634-0245",
    details: { type: "SCORE" },
    source: "score.org",
    source_id: "score-denver",
  },
  {
    name: "SCORE Houston",
    short_description: "Free business mentoring for Greater Houston entrepreneurs.",
    description: "SCORE Houston provides free business counseling and workshops to entrepreneurs in the Greater Houston area.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    city: "Houston",
    state: "TX",
    zip: "77002",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/houston",
    phone: "1-800-634-0245",
    details: { type: "SCORE" },
    source: "score.org",
    source_id: "score-houston",
  },
  {
    name: "SCORE Los Angeles",
    short_description: "Free business mentoring for Los Angeles area entrepreneurs.",
    description: "SCORE Los Angeles provides free, confidential business mentoring and workshops to help small businesses start and grow in the Los Angeles metropolitan area.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    city: "Los Angeles",
    state: "CA",
    zip: "90001",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/losangeles",
    phone: "1-800-634-0245",
    details: { type: "SCORE" },
    source: "score.org",
    source_id: "score-losangeles",
  },
  {
    name: "SCORE Miami",
    short_description: "Free business mentoring for Miami-Dade entrepreneurs.",
    description: "SCORE Miami provides free business counseling and workshops to entrepreneurs in Miami-Dade County.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    city: "Miami",
    state: "FL",
    zip: "33101",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/miami",
    phone: "1-800-634-0245",
    details: { type: "SCORE" },
    source: "score.org",
    source_id: "score-miami",
  },
  {
    name: "SCORE New York City",
    short_description: "Free business mentoring for NYC entrepreneurs.",
    description: "SCORE NYC provides free, confidential business mentoring and workshops to help small businesses start and grow in New York City.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    city: "New York",
    state: "NY",
    zip: "10001",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/nyc",
    phone: "1-800-634-0245",
    details: { type: "SCORE" },
    source: "score.org",
    source_id: "score-nyc",
  },
  {
    name: "SCORE Philadelphia",
    short_description: "Free business mentoring for Philadelphia area entrepreneurs.",
    description: "SCORE Philadelphia provides free business counseling and workshops to entrepreneurs in the Philadelphia metropolitan area.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    city: "Philadelphia",
    state: "PA",
    zip: "19101",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/philadelphia",
    phone: "1-800-634-0245",
    details: { type: "SCORE" },
    source: "score.org",
    source_id: "score-philadelphia",
  },
  {
    name: "SCORE Phoenix",
    short_description: "Free business mentoring for Phoenix area entrepreneurs.",
    description: "SCORE Phoenix provides free, confidential business mentoring and workshops to help small businesses start and grow in the Phoenix metropolitan area.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    city: "Phoenix",
    state: "AZ",
    zip: "85001",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/phoenix",
    phone: "1-800-634-0245",
    details: { type: "SCORE" },
    source: "score.org",
    source_id: "score-phoenix",
  },
  {
    name: "SCORE San Diego",
    short_description: "Free business mentoring for San Diego area entrepreneurs.",
    description: "SCORE San Diego provides free business counseling and workshops to entrepreneurs in San Diego County.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    city: "San Diego",
    state: "CA",
    zip: "92101",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/sandiego",
    phone: "1-800-634-0245",
    details: { type: "SCORE" },
    source: "score.org",
    source_id: "score-sandiego",
  },
  {
    name: "SCORE San Francisco",
    short_description: "Free business mentoring for San Francisco Bay Area entrepreneurs.",
    description: "SCORE San Francisco provides free, confidential business mentoring and workshops to help small businesses start and grow in the San Francisco Bay Area.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    city: "San Francisco",
    state: "CA",
    zip: "94102",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/sanfrancisco",
    phone: "1-800-634-0245",
    details: { type: "SCORE" },
    source: "score.org",
    source_id: "score-sanfrancisco",
  },
  {
    name: "SCORE Seattle",
    short_description: "Free business mentoring for Seattle area entrepreneurs.",
    description: "SCORE Seattle provides free business counseling and workshops to entrepreneurs in the Seattle metropolitan area.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    city: "Seattle",
    state: "WA",
    zip: "98101",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/seattle",
    phone: "1-800-634-0245",
    details: { type: "SCORE" },
    source: "score.org",
    source_id: "score-seattle",
  },
  {
    name: "SCORE Washington DC",
    short_description: "Free business mentoring for Washington DC entrepreneurs.",
    description: "SCORE Washington DC provides free, confidential business mentoring and workshops to help small businesses start and grow in the Washington DC area.",
    category: "sba",
    subcategories: ["mentorship", "training", "workshops"],
    city: "Washington",
    state: "DC",
    zip: "20001",
    country: "USA",
    is_remote: true,
    is_nationwide: false,
    website: "https://www.score.org/washingtondc",
    phone: "1-800-634-0245",
    details: { type: "SCORE" },
    source: "score.org",
    source_id: "score-washingtondc",
  },
];

// Export all SBA resources
export const allSBAResources = [...vbocListings, ...scoreListings];
